---
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  app-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-nginx
  template:
    metadata:
      labels:
        app: app-nginx
    spec:
      containers:
        - name: app-nginx
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: app-volume
          resources:
            requests:
              memory: 500Mi
              cpu: 50m
            limits:
              memory: 1500Mi
              cpu: 100m
          livenessProbe:
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 80
              path: /
            initialDelaySeconds: 10
            periodSeconds: 5
      terminationGracePeriodSeconds: 60
      volumes:
        - name: app-volume
          persistentVolumeClaim:
            claimName: efs-claim